export const state = {
  map: null,
  projectLayers: null,
  casingLayers: null,
  basemapLayers: null,
  cityMarkers: [],
  projects: [],
  overlaps: [],
  selectedOverlapId: null,
  timelineYear: null,
  basemap: null,
  meta: null,
  filterRequest: 0,
  filterAbort: null,
};
